# Generated by Django 4.2.1 on 2023-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_videos_streamingplatform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='usernamefb',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='videoid',
        ),
        migrations.AlterField(
            model_name='videos',
            name='embeedlink',
            field=models.URLField(blank=True, null=True, verbose_name='Embed Link of Posts or Video'),
        ),
    ]
