# Generated by Django 6.0.4 on 2026-04-16 09:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_videos_usernamefb_remove_videos_videoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='colourback',
            field=colorfield.fields.ColorField(blank=True, default='#496D89', image_field=None, max_length=25, null=True, samples=None, verbose_name='colourback'),
        ),
        migrations.AlterField(
            model_name='year',
            name='colourtext',
            field=colorfield.fields.ColorField(blank=True, default='#FFF00C', image_field=None, max_length=25, null=True, samples=None, verbose_name='colourtext'),
        ),
    ]
